// JavaScript Algorithms and Data Structures Masterclass
// INTRO NOTES

// Instructor: Colte Steele
// https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass

// BIG O NOTATION
// ANALYZING PERFORMANCE OF ARRAYS AND OBJECTS
// PROBLEM SOLVING APPROACH
// PROBLEM SOLVING PATTERNS
// OPTIONAL CHALLENGES
// RECURSION
// RECURSION PROBLEM SET
// OPTIONAL RECURSION CHALLENGES
// SEARCHING ALGORITHMS
// BUBBLE SORT
// SELECTION SORT
// INSERTION SORT
// COMPARING BUBBLE, SELECTION, INSERTION SORT
// MERGE SORT
// QUICK SORT
// RADIX SORT

// DATA STRUCTURES INTRO
// SINGLY LINKED LISTS
// DOUBLY LINKED LISTS
// STACKS AND QUEUES
// BINARY SEARCH TREE
// TREE TRAVERSAL
// BINARY HEAPS
// HASH TABLES
// GRAPHS
// GRAPH TRAVERSAL
// DIJKSTRA'S ALG
// DYNAMIC PROGRAMMING